---
- name: Download the SHA256 sums
  get_url:
    url: "https://cdimage.ubuntu.com/ubuntu-server/focal/daily-live/current/SHA256SUMS"
    dest: "{{ target_dir }}"

- name: Get the SHA256 sum for the {{ iso_arch }} ISO
  shell:
    cmd: "grep {{ iso_arch }}.iso {{ target_dir }}/SHA256SUMS | cut -d ' ' -f1"
  changed_when: false
  register: sha256sum

- name: Download the latest Ubuntu Server 20.04 {{ iso_arch }} ISO
  get_url:
    url: "https://cdimage.ubuntu.com/ubuntu-server/focal/daily-live/current/focal-live-server-{{ iso_arch }}.iso"
    dest: "{{ target_dir }}/focal-live-server-{{ iso_arch }}.iso"
    checksum: "sha256:{{ sha256sum.stdout }}"

- name: Download the GPG keys
  get_url:
    url: "https://cdimage.ubuntu.com/ubuntu-server/focal/daily-live/current/SHA256SUMS.gpg"
    dest: "{{ target_dir }}"

- name: Check if dirmngr is running
  shell:
    cmd: pgrep dirmngr
  failed_when: false
  changed_when: false
  register: dirmngr_status

- name: Launch dirmngr if it isn't running
  shell:
    cmd: "dirmngr --daemon"
  when: dirmngr_status.rc != 0

- name: Import the GPG key
  shell:
    cmd: "gpg -q --no-default-keyring --keyring '{{ target_dir }}/{{ ubuntu_gpg_key }}.keyring' --keyserver 'hkp://keyserver.ubuntu.com' --recv-keys {{ ubuntu_gpg_key }}"
    creates:
     - "{{ target_dir }}/{{ ubuntu_gpg_key }}.keyring"
     - "{{ target_dir }}/{{ ubuntu_gpg_key }}.keyring~"
  ignore_errors: yes

- name: Verify the GPG key
  shell:
    cmd: "gpg -q --keyring '{{ target_dir }}/{{ ubuntu_gpg_key }}.keyring' --verify '{{ target_dir }}/SHA256SUMS.gpg' '{{ target_dir }}/SHA256SUMS' 2>/dev/null"
  ignore_errors: yes

- name: Kill dirmngr if we launched it
  shell:
    cmd: "pkill dirmngr"
  when: dirmngr_status.rc != 0
