---  
- name: Get the file size of the ISO
  stat:
    path: "{{ target_dir }}/ubuntu_autoinstall.iso"
  register: iso

- name: Disconnect the current drive
  uri:
    url: "http://{{ pikvm_address }}/api/msd/set_connected?connected=0"
    method: POST
    status_code: [ 400, 200 ]
    headers:
      X-KVMD-User: "{{ pikvm_username }}"
      X-KVMD-Passwd: "{{ pikvm_password }}"
  register: response
  changed_when: response.json is not search("MsdDisconnectedError")

- name: Remove the previous ISO
  uri:
    url: "http://{{ pikvm_address }}/api/msd/remove?image=ubuntu_autoinstall.iso"
    status_code: [ 400, 200 ]
    method: POST
    headers:
      X-KVMD-User: "{{ pikvm_username }}"
      X-KVMD-Passwd: "{{ pikvm_password }}"
  register: response
  changed_when: response.json is not search("MsdUnknownImageError")

- name: Upload the ISO to PiKVM
  shell:
    cmd: "curl --location --request POST '{{ pikvm_address }}/api/msd/write' --header 'X-KVMD-User: {{ pikvm_username }}' --header 'X-KVMD-Passwd: {{ pikvm_password }}' --form 'image=ubuntu_autoinstall.iso' --form 'size={{ iso.stat.size | int }}' --form 'data=@{{ target_dir }}/ubuntu_autoinstall.iso'"

- name: Select the ubuntu_autoinstall ISO
  uri:
    validate_certs: no
    url: "http://{{ pikvm_address }}/api/msd/set_params?image=ubuntu_autoinstall.iso"
    method: POST
    headers:
      X-KVMD-User: "{{ pikvm_username }}"
      X-KVMD-Passwd: "{{ pikvm_password }}"

- name: Connect the ISO to the server
  uri:
    validate_certs: no
    url: "http://{{ pikvm_address }}/api/msd/set_connected?connected=true"
    method: POST
    headers:
      X-KVMD-User: "{{ pikvm_username }}"
      X-KVMD-Passwd: "{{ pikvm_password }}"